module ASCII_art where


haskinator_ascii_art :: String
haskinator_ascii_art =
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdsmMMMMMMMMMMMMNmmmmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhs+mMMMMMMmdyo+/:::::::::+sdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdhoohMMNho/::::-----------.--:sNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdyysyh+::--------..........:/:-:hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhyo:------.........``````-:::/:.sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy:-----......````` ```````...:/:.dNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs-.....`...``````````````````-:::---/sMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy...````.```    ```    `      `/::`.`::oydMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm-````` ```   `...-::-..``  ````-..``-::/:+hMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy`````````  .+o::+oosys/::.``````````----://dMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs``` ``.` `+hs/:-.``../y+:----.`    ```.-///odMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy    .-..-oNs/::``..-.--y+://+oo+--:os..--/:/+yNMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/`  ```.::d+:::--..+-`.:o:o+/:yMNNMMh+- `.::/+smMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh:` `.:/:+/:::::::::::.`-:+.:mMMMMMoos/```:/++omMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy:``:/::-`````---...```:/:/NMMMMMosyyo.`:/+++ydNMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh//--.``````-:+o+:``.::-/MMMMMMyoyhhy.:/+++yhhNMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:``````````..:+`-ooo-+MMMMMMm+hhddy/:+++yhhhmMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd.` ``````````....``.hMMMMMMMyohdmd/-:/oyhhhhmMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs-.``   ````.:.```-yMMMMMMMMMdo+/-`-:/s+oyhhhdNMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmdh::.````   `+yy-/sddmmmmmNNNNNmyo/::/+++++shhhhNMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhhhh/:````````-/ohooshhhhyyyyhhhssssyhys++//++ohhhdMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdhhyo+/:::--.``-os+/+yhh+/////++++++++shhhyyyyyyhhmMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhhhyysh/::/::````-o/syhhh+///////////++yhhhhhhhddmMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhhhhyyysy/::-//:.````/ossyhhs+//s//////+oyhhhhdmNMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmddhhhhhysssssssoo::/::.``:+y++ohhhyys+y//oyhhdmmNMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhhhhhhhhysssssooooosy+-:/::.:+/++++ssshyhhhhdmmNMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMdhhhyhhhhssssoooooooooo+//::::::/o+++++sshhdmNMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMdddddysyyyhsooooooooooo++++s//--/:++/////+hmMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMmddddhsoooosoooooooo++++++++++++/::////////+dMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMmdddd/````..-......-/++++++++++//////////////+hMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMmdddhhys+/-.``` ```  `-/++++////////////////:::+mMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMNdddhysooooo+++-   ```````..-/:////////////:::::::hMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMmddhsoooooo+++//` `.    ``..``.::///////::/+ooso+/odMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMNmdddsoossss/..`-..`::  -..-:/--:://///:/+syyys++oshhyNMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMNdddhhhddddd+....:://+-..+:::/:/ooo/:::/+oo///+oyhddy/+mMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMmdddddddddddy/:::/::+oo///++shh::dddyyyyso++oyhdddhy+:/hdMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMmdddddddddddds++++++:+ooo++ohmmm/:ddddyo++osysso++////syhdNMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMNdddddddddddddo++++++//ooooydmmmd-oNdddhhhhhhhhhhyyyyhhsyddmMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMmddddddddddddds++++++/:ooohdddddo-mMmddddhssoooosssyhhyyhhhmMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMNddddddddddddddh+++++++//shddddds:yMMNdddddhhhhhhhhhhhhhhhddNMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMmddddddddddddddds+++++++:shhhhho:smmmmdhhhhhhhhhhhhdddddddddMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMmmmdmmmmmmmmmmmds+++++++:oyhy+/ymmmmmmmddddddddmmmmmddmmmmmMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMNNmmmmmmmmmNNNmhyyyssoo+++/sdmmmmmmmmmmmmmmmmmmmmmmmmmmmNMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmmmmmmmddddddddddmmmmmmmmmmmmmmmmmmmmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmmmmmmmmmmmmmdddmmmmmmmmmmmmmmmmmmmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmmmdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmmmmmmmmmmmmmmmmmmmmmmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmmNMNNmmmmmmmmmmmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmmMMMMMNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMNMMMNNMMMMMMNNNMMMMMMmmmmMMMMMMMMMMMMMMMMMMMMMNNMMMMMNMMMMMMMNNMNMMMMMMMMMMMMMMMM\n"


haskinator_ascii_art_small :: String
haskinator_ascii_art_small =
    "MMMMMMMMMMMMMMMMMMMMMMdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMNhoMMMNdyo+/:::/ohNMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMmyshs/:-----....-::sMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMNy/---.....`````--::+MMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMh-..`.````````````::--+mMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMm.`````  `.--..````..`.:/+mMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMs```` `/o:::/+o:..````..-/+NMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMy  ...+y::.`:./o///s++s-.::odMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMy-`.:/+::--:--.::/MMMho:`-/+hMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMNy:::.```:::.`-:+MMMhsyo./+ohNMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMNh``````.---/:oMMMNshds:+ohhmMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMMNo.``  `.:`./mMMMMmyo:-/ooyhmMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMmhy:`````:s+shdhhhddysoo+++oyhdMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMMdhyo+::-`.+++hh+//+++++ohyyyyhmMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMNmdhhyso/:::.`.+syho+o///+ohddmNNMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMNddhhhysssooo+::-./o+oyyyysydmNNMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMNddyhyysooooooo/+:::/++++ydNNMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMNddyo+oo+++++++++++///////+dMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMNdhho:-..````-/++////////////mMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMmdysooo++. `````.-:///////////hMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMNmdhssy+-.-.-.`.-::://///oososyyyMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMNddddddh/:::/+:/+os:hysooo+oyhhs/yNMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMNdddddddy+++/+ooohmd:mdhsssyssoooshmMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMmdddddddh++++/oyddd+yMdddhyyyyyhhyhmMMMMMMMMMMMMMMM\n\
    \MMMMMMMMNdddddddddo+++/ohhhoommdddhhhhhhhdddNMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMNmmmmmmmmdsooo++soymmmmmddddmmmmmmmMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMNmmmdddhdmmmmmmmmmmmmmmmmmMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMNmmmmmmmmdddmmmmmmmmmmmmmMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMmmmmmmmmmmmmmmmmmmmmmNMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMNmmmmmmmmmmmmmmmmmNMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMMMMMMMMNmmmNNmmmmmmmNNMMMMMMMMMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMNMMMMNMMMNmmNMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMM\n"

haskinator_ascii_art_smallest :: String
haskinator_ascii_art_smallest = 
    "MMMMMMMMMMMMMMmmMMMNmdddNMMMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMNyhy+:----.-+dMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMN+-...`````.-:ymMMMMMMMMMMM\n\
    \MMMMMMMMMMMMM+``````-.` `..`/oNMMMMMMMMM\n\
    \MMMMMMMMMMMMM``.`o+--/+--.`-.:oNMMMMMMMM\n\
    \MMMMMMMMMMMMMy.`:+:----:/dMm+.:+dMMMMMMM\n\
    \MMMMMMMMMMMMMMMy/.``-:.::NMmyy/+sdMMMMMM\n\
    \MMMMMMMMMMMMMMMMm-`  `-.oMMMds:/oydNMMMM\n\
    \MMMMMMMMMMMMMMMmh+-...sohsossossooydMMMM\n\
    \MMMMMMMMMMMMMNmdyso/:.`/yyo+//oydmNMMMMM\n\
    \MMMMMMMMMMMmhhhssooo+/::++oyhdNMMMMMMMMM\n\
    \MMMMMMMMMMmds/++//++++/////+mMMMMMMMMMMM\n\
    \MMMMMMMMMmhyo/: ```-:///////+MMMMMMMMMMM\n\
    \MMMMMMMNdhyy/---.--:////+osysNMMMMMMMMMM\n\
    \MMMMMMNddddh///o+sd+dhsssysoomMMMMMMMMMM\n\
    \MMMMMMmddddh++/+ydhsNddyyyyhhmMMMMMMMMMM\n\
    \MMMMMMmmmmmmyo++sssdmddddddddNMMMMMMMMMM\n\
    \MMMMMMMMMMMMmmmdddddmmmmmmmmmMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMmmmmmmmmmmmmmmmMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMNmmmmmmmmmmNNMMMMMMMMMMMMM\n\
    \MMMMMMMMMMMMMMMNmNMNNNMMMMMMMMMMMMMMMMMM\n"